### PR TITLE
Parse llvm version

### LINKED ISSUE #30: parse rustc's llvm version too
I'm trying to compile C code and link it to my Rust code at the LLVM IR level, to have that work well, clang's version should match rustc's version of LLVM. It would be useful if this crate would parse that.

### PR DESCRIPTION
**Pull request by programmerjake**
Parse LLVM version too

Fixes #30

If you like, I can add a separate method to parse the LLVM version string and/or produce more specific errors on parse failure.

### CODE REVIEW

**Comment by djc** [comment]
Thank you for working on this! Is there a reason not to reuse semver::Version and its parser here?

**Comment by programmerjake** [comment]
> Thank you for working on this! Is there a reason not to reuse semver::Version and its parser here?

Because older LLVM versions don't follow semver, also because the version printed by rustc only has major and minor parts, semver requires major, minor, and patch.

File: src/lib.rs [hunk 1]
```diff
@@ -193,6 +221,42 @@ pub fn version_meta_for(verbose_version_string: &str) -> Result<VersionMeta> {
...
+                return Err(Error::UnexpectedVersionFormat);
+            }
+        } else if major < 4 {
+            // LLVM versions earlier than 4.0 have significant minor versions, so require the minor version in this case.
+            return Err(Error::UnexpectedVersionFormat);
+        }
+        Some(LLVMVersion { major, minor })
+    } else {
+        None
+    };
```
Comment (djc) [inline src/lib.rs]: I would propose we move this code into an `LLVMVersion::from_str() -> Result<Self, Error>` static method. Also, I'd suggest using `splitn()` rather than `split()` and ideally structuring the rest of the code as a `map()` combinator call on the result of the `splitn()` return value. I think this should obviate the need for the nested function.

File: src/lib.rs [hunk 2]
```diff
@@ -85,6 +85,28 @@ pub enum Channel {
...
 
+/// LLVM version
+///
+/// LLVM's version numbering scheme is not semvar compatible until version 4.0
+///
+/// rustc [just prints the major and minor versions], so other parts of the version are not included.
+///
+/// [just prints the major and minor versions]: https://github.com/rust-lang/rust/blob/b5c9e2448c9ace53ad5c11585803894651b18b0a/compiler/rustc_codegen_llvm/src/llvm_util.rs#L173-L178
+#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
+pub struct LLVMVersion {
```
Comment (djc) [inline src/lib.rs]: Let's name this `LlvmVersion` in keeping with the API guidelines.

**Review by djc — COMMENTED** [review]
I think this can be structured a bit differently to make it easier to follow, let me know what you think!

File: src/lib.rs (hunk 1 above)
Comment (programmerjake) [reply src/lib.rs]: I followed your suggestion, though I don't think `splitn` would be best since I also added more specific errors. I ended up changing it back to `split` since it makes the code clearer.

File: src/lib.rs [hunk 3]
```diff
@@ -93,20 +93,53 @@ pub enum Channel {
...
+impl FromStr for LlvmVersion {
+    type Err = LlvmVersionParseError;
+
+    fn from_str(s: &str) -> Result<Self, Self::Err> {
+        let mut parts = s
+            .splitn(3, '.')
+            .map(|part| -> Result<u64, LlvmVersionParseError> {
+                match part.as_bytes() {
+                    // check for at least 2 characters to avoid erroring on "0"
+                    [b'0', _, ..] => Err(LlvmVersionParseError::ComponentMustNotHaveLeadingZeros),
```
Comment (djc) [inline src/lib.rs]: I think this is a very recent language feature, right? Can we do something less elegant that compiles on older Rust? I know there's no defined MSRV here but I know at least one project that depends on rustc-version that tries to work on something as old as 1.34.

**Comment by djc** [comment]
Otherwise this is looking great, BTW!

**Comment by programmerjake** [comment]
Well, rust 1.34.0 runs into this issue:
```
    Updating crates.io index
   Compiling ucd-trie v0.1.3
   Compiling doc-comment v0.3.3
   Compiling pest v2.1.3
   Compiling semver-parser v0.10.1
error[E0658]: non-builtin inner attributes are unstable (see issue #54726)
 --> /home/jacob/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
  |
4 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
```

**Comment by programmerjake** [comment]
The first rustc version where semver-parser builds is 1.44.0, which also supports the slice matching syntax I used.

**Comment by programmerjake** [comment]
Should I add a commit to add 1.44.0 to .travis.yml?

**Comment by djc** [comment]
Nope, I'm fixing that: https://github.com/steveklabnik/semver-parser/pull/54.

File: src/lib.rs (hunk 3 above)
Comment (programmerjake) [reply src/lib.rs]: Removed the slice matching

**Comment by djc** [comment]
Thanks for all this!
